### ISSUE TITLE
Enum is not imported properly

### ISSUE THREAD

**Issue by alexander-myltsev** [scala/nanotest-strawman#40]
In the source file I define enum:

```scala
enum MyEnum {
  case A, B
}
```

Then I try to test it:

```scala
object MyTest extends BasicTestSuite {
  test("enum") {
    assert(!MyEnum.A.equals(MyEnum.B))
  }
}
```

The test throws: 

```scala
[error] java.lang.NoSuchFieldError: A
[error] 	at io.okama.portfolio.MyTest$.$init$$$anonfun$1(RegistryIntegrationTest.scala:15)
[error] 	at verify.BasicTestSuite.test$$anonfun$1(BasicTestSuite.scala:23)
[error] 	at verify.TestSpec$.liftedTree4$1(TestSpec.scala:48)
[error] 	at verify.TestSpec$.sync$$anonfun$1(TestSpec.scala:57)
[error] 	at verify.TestSpec.apply(TestSpec.scala:22)
[error] 	at verify.Properties.liftedTree1$1(Properties.scala:34)
[error] 	at verify.Properties.liftedTree2$3(Properties.scala:38)
[error] 	at verify.Properties.iterator$$anonfun$2$$anonfun$1(Properties.scala:50)
[error] 	at verify.TestSpec.apply(TestSpec.scala:22)
[error] 	at verify.runner.Task.loop$2(Task.scala:51)
[error] 	at verify.runner.Task.$anonfun$2(Task.scala:66)
[error] 	at scala.Option.fold(Option.scala:263)
[error] 	at verify.runner.Task.execute(Task.scala:68)
[error] 	at verify.runner.Task.execute(Task.scala:76)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[error] 	at sbt.TestRunner.run(TestFramework.scala:124)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:294)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

If I define the enum in the test, it works as expected.

**Comment by Regan-Koopmans** [comment]
Hi @alexander-myltsev , I was not able to reproduce this. I defined my enum in this manner:

```scala
object MyEnum extends Enumeration {
  val A, B = Value
}
```

And then this test passed:

```scala
import verify._

object TestEnum extends BasicTestSuite {
  test("enum") {
    assert(!MyEnum.A.equals(MyEnum.B))
  }
}

```

Let me know whether you are still encountering issues. If so, please share the Scala version you are using.
